<?php
//storing 3 letter lowercase month in variable for variable image extention name
$monthName = date('M');
$monthName = strtolower($monthName);
$monthNumber = date('n');

//array to store variable alt text
$specials_alt = array(
    'January special: Random January Image',
    'February special: Random February Image',
    'March special: Random March Image',
    'April special: Random April Image',
    'May special: Random May Image',
    'June special: Random June Image',
    'July special: Random July Image',
    'August special: Random August Image',
    'September special: Random September Image',
    'October special: Random October Image',
    'November special: Random November Image',
    'December special: Random December Image'
     );
?>


<?php require 'includes/toppage.php'; //include for header ?>
        <div class="main-container">
            <div class="main wrapper clearfix">

                <article>
                    <header>
                        <h1>Page 2 to test PHP doc relativity</h1>
                        <!--php changeds image by echoing monthname variable along with changing alt text-->
                        <img src="img/monthimg/special_<?php echo $monthName; ?>.jpg" alt="<?php echo $specials_alt[$monthNumber - 1]; ?>" id="randomImg">
                        <p>The image above is generated by month name using the php date('n') to change the file extension.</p>
                    </header>
                    <section>
                        <h2>Animated Banner</h2>
                        <p>For my banner I used multiple css3 transitions and javascript to animate the banner seen <a href="moraybanner.html" title="Moray Creative Banner">here</a>.</p>
                    </section>
                    <section>
                        <h2>CUBE gallery</h2>
                        <p>Animated cube gallery using css3 trasitions and transforms. Created by following lynda.com <i>CSS: Transitions and Transforms with Joseph Lowery</i> tutorials. Click <a href="pictureCube.html" title="Moray Creative Cube">here</a> to view.</p>
                    </section>
                    <section>
                        <h2>3D Carousel</h2>
                        <p>Animated carousel gallery using css3 trasitions and transforms. Created by following lynda.com <i>CSS: Transitions and Transforms with Joseph Lowery</i> tutorials. Click <a href="slideCarousel.html" title="Moray Creative Carousel">here</a> to view.</p>
                    </section>
                    <footer>
                        <h3>article footer h3</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sodales urna non odio egestas tempor. Nunc vel vehicula ante. Etiam bibendum iaculis libero, eget molestie nisl pharetra in. In semper consequat est, eu porta velit mollis nec. Curabitur posuere enim eget turpis feugiat tempor.</p>
                    </footer>
                </article>

                <aside id="sideBox">
                    <img src="img/moraylogo.png" alt="Moray Creative Logo" title="Moray Creative Logo" id="MorayLogo">
                    <h3>About</h3>
                    <p>Moray Creative is the design alias of Jeremy McClelland. Jeremy is a graphic artist from Charleston, SC with a passion for design and illustration. Over the past eight years he has worked for several print houses and has been actively freelancing in the Charleston area.<br><br>

                    Currently, Jeremy works at Nelson Printing; designing and prepping projects for press. Shifting his focus from print, Jeremy is sharpening his skills as a frontend developer.</p>
                </aside>

            </div> <!-- #main -->
        </div> <!-- #main-container -->

<?php require 'includes/footer.php'; //include for footer ?>
